# Generated by Django 2.0.6 on 2019-03-28 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bbmAdmin',
            fields=[
                ('adminEmail', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('adminName', models.CharField(default='', max_length=255)),
                ('adminPhone', models.BigIntegerField(unique=True)),
                ('adminImage', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bbmBankManager',
            fields=[
                ('managerEmail', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('managerName', models.CharField(default='', max_length=255)),
                ('managerPhone', models.BigIntegerField(unique=True)),
                ('managerImage', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bbmBlood',
            fields=[
                ('bloodCode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('bloodCost', models.BigIntegerField()),
                ('bloodType', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='bbmBloodBank',
            fields=[
                ('bbkBloodType', models.CharField(default='', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('bbkAvailable', models.CharField(default='Yes', max_length=255)),
                ('bbkId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app2.bbmBlood')),
            ],
        ),
        migrations.CreateModel(
            name='bbmDonar',
            fields=[
                ('donarname', models.CharField(default='', max_length=255)),
                ('donaremail', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('donarpassword', models.CharField(default='', max_length=255)),
                ('donarcontactno', models.BigIntegerField(unique=True)),
                ('donarage', models.BigIntegerField()),
                ('donarimage', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bbmHospitals',
            fields=[
                ('hosName', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('hosPhone', models.BigIntegerField(unique=True)),
                ('hosAddress', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='bbmUser1',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bbmdonar',
            name='donarid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app2.bbmUser1'),
        ),
        migrations.AddField(
            model_name='bbmbloodbank',
            name='bbkhosId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app2.bbmHospitals'),
        ),
        migrations.AddField(
            model_name='bbmbloodbank',
            name='bbkmgId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app2.bbmBankManager'),
        ),
        migrations.AddField(
            model_name='bbmblood',
            name='bloodId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app2.bbmDonar'),
        ),
        migrations.AddField(
            model_name='bbmbankmanager',
            name='managerId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app2.bbmUser1'),
        ),
        migrations.AddField(
            model_name='bbmadmin',
            name='adminId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app2.bbmUser1'),
        ),
    ]
