# Generated by Django 2.0.6 on 2019-04-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbmadmin',
            name='adminPassword',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='bbmbankmanager',
            name='managerPassword',
            field=models.CharField(default='', max_length=255),
        ),
    ]
