# Generated by Django 2.0.6 on 2019-04-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20190405_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbmadmin',
            old_name='adminName',
            new_name='adminame',
        ),
        migrations.RenameField(
            model_name='bbmadmin',
            old_name='adminEmail',
            new_name='adminemail',
        ),
        migrations.RenameField(
            model_name='bbmadmin',
            old_name='adminId',
            new_name='adminid',
        ),
        migrations.RenameField(
            model_name='bbmadmin',
            old_name='adminImage',
            new_name='adminimage',
        ),
        migrations.RenameField(
            model_name='bbmadmin',
            old_name='adminPassword',
            new_name='adminpassword',
        ),
        migrations.RenameField(
            model_name='bbmadmin',
            old_name='adminPhone',
            new_name='adminphone',
        ),
        migrations.RenameField(
            model_name='bbmbankmanager',
            old_name='managerEmail',
            new_name='manageremail',
        ),
        migrations.RenameField(
            model_name='bbmbankmanager',
            old_name='managerId',
            new_name='managerid',
        ),
        migrations.RenameField(
            model_name='bbmbankmanager',
            old_name='managerName',
            new_name='managername',
        ),
        migrations.RenameField(
            model_name='bbmbankmanager',
            old_name='managerPassword',
            new_name='managerpassword',
        ),
    ]
