# Generated by Django 2.0.6 on 2019-04-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20190405_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bbmbankmanager',
            old_name='managerImage',
            new_name='managerimage',
        ),
        migrations.RenameField(
            model_name='bbmbankmanager',
            old_name='managerPhone',
            new_name='managerphone',
        ),
    ]
