# Generated by Django 2.0.6 on 2019-04-08 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_auto_20190405_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbmadmin',
            name='adminid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app2.bbmUser1'),
        ),
        migrations.AlterField(
            model_name='bbmbankmanager',
            name='managerid',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app2.bbmUser1'),
        ),
        migrations.AlterField(
            model_name='bbmdonar',
            name='donarid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app2.bbmUser1'),
        ),
    ]
