# Generated by Django 2.0.6 on 2019-04-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_auto_20190408_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbmadmin',
            name='adminimage',
        ),
        migrations.RemoveField(
            model_name='bbmbankmanager',
            name='managerimage',
        ),
    ]
