# Generated by Django 2.0.6 on 2019-04-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_auto_20190412_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbmdonar',
            name='donarotp',
        ),
        migrations.RemoveField(
            model_name='bbmdonar',
            name='donarotptime',
        ),
    ]
