# Generated by Django 2.0.6 on 2019-04-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_bbmdonar_donarotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbmdonar',
            name='donarotptime',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
